export type IngredienteRef = {
  nombre: string
  aliases?: string[]
  categoria: 'Carnes' | 'Mariscos' | 'Verduras' | 'Frutas' | 'Lácteos' | 'Granos' | 'Otros'
  rendimiento: number        // % merma REAL (lo que va a la basura)
  unidad: string
  nota: string               // qué va a la basura
  subproducto?: string       // si las partes "descartadas" se pueden aprovechar
}

export const RENDIMIENTOS_CATALOGO: IngredienteRef[] = [
  // ─── CARNES ────────────────────────────────────────────────
  {
    nombre: 'Pollo entero',
    aliases: ['pollo', 'pollo entero'],
    categoria: 'Carnes',
    rendimiento: 88,
    unidad: 'kg',
    nota: 'Descarte real: vísceras no comestibles (~12%). Plumas si las hay.',
    subproducto: 'Los huesos y carcasa NO son merma — úsalos para fondo de pollo.',
  },
  {
    nombre: 'Pechuga de pollo',
    aliases: ['pechuga'],
    categoria: 'Carnes',
    rendimiento: 93,
    unidad: 'kg',
    nota: 'Descarte: cartílagos y grasa excesiva (~7%).',
  },
  {
    nombre: 'Muslo y pierna de pollo',
    aliases: ['muslo', 'pierna pollo'],
    categoria: 'Carnes',
    rendimiento: 72,
    unidad: 'kg',
    nota: 'Descarte real: piel (si se retira) y cartílagos.',
    subproducto: 'Los huesos son sub-producto aprovechable para caldo.',
  },
  {
    nombre: 'Res (filete)',
    aliases: ['filete', 'filete de res', 'lomo'],
    categoria: 'Carnes',
    rendimiento: 88,
    unidad: 'kg',
    nota: 'Descarte: grasa exterior excesiva y membrana (~12%).',
    subproducto: 'Los recortes de carne pueden usarse para caldo o picadillo.',
  },
  {
    nombre: 'Res (costilla)',
    aliases: ['costilla', 'costilla de res'],
    categoria: 'Carnes',
    rendimiento: 68,
    unidad: 'kg',
    nota: 'Alto porcentaje de hueso (~32%). El hueso NO es merma.',
    subproducto: 'Los huesos son la base de caldos y consomés.',
  },
  {
    nombre: 'Res (molida)',
    aliases: ['carne molida', 'res molida'],
    categoria: 'Carnes',
    rendimiento: 75,
    unidad: 'kg',
    nota: 'Pierde líquido y grasa al cocinar (~25%). Merma es al cocinar, no al limpiar.',
  },
  {
    nombre: 'Cerdo (lomo)',
    aliases: ['lomo de cerdo'],
    categoria: 'Carnes',
    rendimiento: 88,
    unidad: 'kg',
    nota: 'Descarte: grasa y membrana exterior (~12%).',
  },
  {
    nombre: 'Cerdo (costilla)',
    aliases: ['costilla de cerdo'],
    categoria: 'Carnes',
    rendimiento: 65,
    unidad: 'kg',
    nota: 'Alto porcentaje de hueso.',
    subproducto: 'Huesos para caldo de cerdo.',
  },
  {
    nombre: 'Tocino',
    aliases: ['bacon', 'tocino'],
    categoria: 'Carnes',
    rendimiento: 75,
    unidad: 'kg',
    nota: 'Pierde hasta 25% de grasa al cocinar.',
  },
  {
    nombre: 'Chorizo',
    aliases: ['chorizo'],
    categoria: 'Carnes',
    rendimiento: 85,
    unidad: 'kg',
    nota: 'Pierde grasa al cocinar y la tripa (si la lleva).',
  },

  // ─── MARISCOS ───────────────────────────────────────────────
  {
    nombre: 'Camarón entero',
    aliases: ['camarón', 'camaron', 'camarones'],
    categoria: 'Mariscos',
    rendimiento: 50,
    unidad: 'kg',
    nota: 'Cabeza y cáscara representan ~50% del peso.',
    subproducto: 'La cabeza y cáscara son el mejor bisque/caldo de mariscos. No las tires.',
  },
  {
    nombre: 'Camarón sin cabeza',
    aliases: ['camarón pelado'],
    categoria: 'Mariscos',
    rendimiento: 75,
    unidad: 'kg',
    nota: 'Cáscara ~20% y vena ~5%.',
    subproducto: 'Las cáscaras dan sabor a fondos de mariscos.',
  },
  {
    nombre: 'Pescado entero',
    aliases: ['pescado', 'huachinango', 'robalo', 'tilapia'],
    categoria: 'Mariscos',
    rendimiento: 45,
    unidad: 'kg',
    nota: 'Cabeza, espinas y piel representan ~55% del peso.',
    subproducto: 'Espinas y cabeza → fumet de pescado. No son merma si se usan.',
  },
  {
    nombre: 'Filete de pescado',
    aliases: ['filete de pescado'],
    categoria: 'Mariscos',
    rendimiento: 95,
    unidad: 'kg',
    nota: 'Descarte mínimo: piel si se retira y bordes (~5%).',
  },
  {
    nombre: 'Pulpo',
    aliases: ['pulpo'],
    categoria: 'Mariscos',
    rendimiento: 60,
    unidad: 'kg',
    nota: 'Pierde mucho líquido al cocer (~40%). Boca y pico son descarte real.',
  },
  {
    nombre: 'Calamar',
    aliases: ['calamar'],
    categoria: 'Mariscos',
    rendimiento: 65,
    unidad: 'kg',
    nota: 'Descarte: piel, pluma interna, cabeza y tentáculos (si no se usan).',
    subproducto: 'Tentáculos pueden usarse si la receta lo permite.',
  },

  // ─── VERDURAS ───────────────────────────────────────────────
  {
    nombre: 'Tomate',
    aliases: ['tomate', 'jitomate'],
    categoria: 'Verduras',
    rendimiento: 90,
    unidad: 'kg',
    nota: 'Descarte: tallo y pedúnculo (~10%).',
  },
  {
    nombre: 'Cebolla',
    aliases: ['cebolla'],
    categoria: 'Verduras',
    rendimiento: 88,
    unidad: 'kg',
    nota: 'Descarte: cáscara seca y capas más externas (~12%).',
  },
  {
    nombre: 'Ajo',
    aliases: ['ajo'],
    categoria: 'Verduras',
    rendimiento: 82,
    unidad: 'kg',
    nota: 'Descarte: cáscara (~18%).',
  },
  {
    nombre: 'Papa',
    aliases: ['papa', 'patata'],
    categoria: 'Verduras',
    rendimiento: 80,
    unidad: 'kg',
    nota: 'Descarte: cáscara (~15%) y partes dañadas (~5%). Si se deja con cáscara, 95%.',
  },
  {
    nombre: 'Zanahoria',
    aliases: ['zanahoria'],
    categoria: 'Verduras',
    rendimiento: 85,
    unidad: 'kg',
    nota: 'Descarte: cáscara y puntas (~15%).',
    subproducto: 'La cáscara puede usarse en caldos de verduras.',
  },
  {
    nombre: 'Apio',
    aliases: ['apio'],
    categoria: 'Verduras',
    rendimiento: 75,
    unidad: 'kg',
    nota: 'Descarte: hojas (si no se usan) y base (~25%).',
    subproducto: 'Hojas y base para caldos de verduras.',
  },
  {
    nombre: 'Pimiento (chile morrón)',
    aliases: ['pimiento', 'morrón', 'chile morrón'],
    categoria: 'Verduras',
    rendimiento: 83,
    unidad: 'kg',
    nota: 'Descarte: semillas, nervaduras y rabo (~17%).',
  },
  {
    nombre: 'Chile poblano',
    aliases: ['poblano', 'chile poblano'],
    categoria: 'Verduras',
    rendimiento: 78,
    unidad: 'kg',
    nota: 'Descarte: piel asada, semillas y nervaduras (~22%).',
  },
  {
    nombre: 'Aguacate',
    aliases: ['aguacate', 'palta'],
    categoria: 'Verduras',
    rendimiento: 65,
    unidad: 'kg',
    nota: 'Descarte: hueso (~15%) y cáscara (~20%). Mucho peso sin valor.',
  },
  {
    nombre: 'Lechuga',
    aliases: ['lechuga'],
    categoria: 'Verduras',
    rendimiento: 80,
    unidad: 'kg',
    nota: 'Descarte: hojas exteriores marchitas y base (~20%).',
  },
  {
    nombre: 'Espinaca',
    aliases: ['espinaca'],
    categoria: 'Verduras',
    rendimiento: 85,
    unidad: 'kg',
    nota: 'Descarte: tallos gruesos y hojas dañadas (~15%).',
  },
  {
    nombre: 'Brócoli',
    aliases: ['brócoli', 'brocoli'],
    categoria: 'Verduras',
    rendimiento: 60,
    unidad: 'kg',
    nota: 'Descarte: tallo grueso si no se usa (~40%).',
    subproducto: 'El tallo pelado es completamente comestible — úsalo en cremas o stir-fry.',
  },
  {
    nombre: 'Champiñones',
    aliases: ['champiñones', 'hongos', 'setas'],
    categoria: 'Verduras',
    rendimiento: 90,
    unidad: 'kg',
    nota: 'Descarte: base del tallo y partes dañadas (~10%).',
  },
  {
    nombre: 'Elote / Maíz',
    aliases: ['elote', 'maíz', 'mazorca'],
    categoria: 'Verduras',
    rendimiento: 50,
    unidad: 'kg',
    nota: 'El olote (corazón) y la hoja representan ~50%.',
    subproducto: 'La hoja sirve para tamales. El olote puede dar humo para asar.',
  },
  {
    nombre: 'Chayote',
    aliases: ['chayote'],
    categoria: 'Verduras',
    rendimiento: 85,
    unidad: 'kg',
    nota: 'Descarte: cáscara y semilla (~15%).',
  },

  // ─── FRUTAS ─────────────────────────────────────────────────
  {
    nombre: 'Limón',
    aliases: ['limón', 'limon'],
    categoria: 'Frutas',
    rendimiento: 35,
    unidad: 'kg',
    nota: 'Si solo usas el jugo, la cáscara y bagazo son descarte. Si usas la ralladura, sube a 80%.',
    subproducto: 'La cáscara tiene valor para ralladura, aceite esencial y zest.',
  },
  {
    nombre: 'Naranja',
    aliases: ['naranja'],
    categoria: 'Frutas',
    rendimiento: 45,
    unidad: 'kg',
    nota: 'Solo el jugo representa ~45% del peso. La cáscara es sub-producto valioso.',
    subproducto: 'Cáscara para zest, licores, salsas agridulces.',
  },
  {
    nombre: 'Mango',
    aliases: ['mango'],
    categoria: 'Frutas',
    rendimiento: 60,
    unidad: 'kg',
    nota: 'Descarte: hueso (~15%) y cáscara (~25%).',
    subproducto: 'Del hueso se pueden hacer aguas o atoles. La cáscara tiene pectina.',
  },
  {
    nombre: 'Piña',
    aliases: ['piña', 'ananá'],
    categoria: 'Frutas',
    rendimiento: 55,
    unidad: 'kg',
    nota: 'Cáscara (~20%) y corazón (~25%) son descarte si no se usan.',
    subproducto: 'Cáscara y corazón → agua de piña, tepache, vinagre.',
  },
  {
    nombre: 'Papaya',
    aliases: ['papaya'],
    categoria: 'Frutas',
    rendimiento: 65,
    unidad: 'kg',
    nota: 'Cáscara (~15%) y semillas (~20%) son descarte típico.',
    subproducto: 'Las semillas de papaya tienen uso en aderezos y la medicina popular.',
  },
  {
    nombre: 'Plátano',
    aliases: ['plátano', 'banano', 'banana'],
    categoria: 'Frutas',
    rendimiento: 68,
    unidad: 'kg',
    nota: 'Cáscara representa ~32% del peso.',
  },

  // ─── LÁCTEOS ────────────────────────────────────────────────
  {
    nombre: 'Huevo',
    aliases: ['huevo', 'huevos'],
    categoria: 'Lácteos',
    rendimiento: 88,
    unidad: 'kg',
    nota: 'La cáscara representa ~12% del peso.',
  },
  {
    nombre: 'Queso fresco',
    aliases: ['queso fresco', 'queso'],
    categoria: 'Lácteos',
    rendimiento: 95,
    unidad: 'kg',
    nota: 'Pérdida mínima por humedad y corteza.',
  },

  // ─── GRANOS ─────────────────────────────────────────────────
  {
    nombre: 'Frijol seco',
    aliases: ['frijol', 'frijoles'],
    categoria: 'Granos',
    rendimiento: 100,
    unidad: 'kg',
    nota: 'Sin merma en seco. Al cocer aumenta de peso (absorbe agua).',
  },
  {
    nombre: 'Arroz',
    aliases: ['arroz'],
    categoria: 'Granos',
    rendimiento: 100,
    unidad: 'kg',
    nota: 'Sin merma. Al cocer 1kg produce ~2.5kg de arroz cocido.',
  },
]

export function buscarIngredienteRef(query: string): IngredienteRef[] {
  if (query.length < 2) return []
  const q = query.toLowerCase().trim()
  return RENDIMIENTOS_CATALOGO.filter(i =>
    i.nombre.toLowerCase().includes(q) ||
    i.aliases?.some(a => a.toLowerCase().includes(q))
  ).slice(0, 6)
}
